"""
Abundance QC Report Generator
================================

Generates abundance_report.html — an interactive Plotly dashboard
summarizing differential tRNA abundance analysis.

Panels:
    1. Volcano plot
    2. MA plot
    3. Top DE features table
    4. Sample PCA from count matrix
"""

import numpy as np
import pandas as pd
from pathlib import Path
from typing import Optional

import plotly.graph_objects as go
import plotly.offline

from trnaseq.qc.report import _discrete_palette


class AbundanceReportGenerator:
    """Generate interactive HTML dashboard for abundance analysis."""

    def __init__(
        self,
        results_df: pd.DataFrame,
        count_matrix: pd.DataFrame,
        control_group: str,
        level: str,
        condition_map: Optional[dict] = None,
    ):
        """
        Parameters
        ----------
        results_df : DataFrame
            DESeq2 results with columns: feature, log2FoldChange, padj,
            baseMean, comparison.
        count_matrix : DataFrame
            samples x features count matrix.
        control_group : str
            Name of the control group.
        level : str
            Aggregation level (transcript, codon, aa).
        condition_map : dict, optional
            {sample_name_unique: condition_group}.
        """
        self.results = results_df.copy() if results_df is not None else pd.DataFrame()
        self.count_matrix = count_matrix.copy()
        self.control_group = control_group
        self.level = level
        self.condition_map = condition_map or {}

    def generate_html_report(self, output_path) -> str:
        """Generate self-contained HTML report."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        panels = []

        p1 = self._panel_volcano()
        if p1:
            panels.append(p1)

        p2 = self._panel_ma()
        if p2:
            panels.append(p2)

        p3 = self._panel_top_de_table()
        if p3:
            panels.append(p3)

        p4 = self._panel_pca()
        if p4:
            panels.append(p4)

        body = '\n'.join(panels)
        plotlyjs = plotly.offline.get_plotlyjs()

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>tRNA Abundance Report</title>
<script>{plotlyjs}</script>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
       margin: 0; padding: 20px 40px; background: #f5f6fa; color: #2d3436; }}
h1 {{ border-bottom: 3px solid #6c5ce7; padding-bottom: 10px; }}
h2 {{ color: #2d3436; margin-top: 40px; }}
.card {{ background: white; border-radius: 8px; padding: 20px; margin: 20px 0;
         box-shadow: 0 2px 8px rgba(0,0,0,0.08); overflow-x: auto; }}
table {{ border-collapse: collapse; width: 100%; font-size: 13px; }}
th {{ background: #6c5ce7; color: white; padding: 8px 12px; text-align: left; }}
td {{ padding: 6px 12px; border-bottom: 1px solid #dfe6e9; }}
tr:hover {{ background: #f0f3f8; }}
.up {{ color: #d63031; font-weight: bold; }}
.down {{ color: #0984e3; font-weight: bold; }}
.footer {{ font-size: 11px; color: #636e72; margin-top: 40px; text-align: center; }}
</style>
</head>
<body>
<h1>tRNA Abundance Dashboard</h1>
<p>Control group: <code>{self.control_group}</code> | Level: <code>{self.level}</code></p>
{body}
<div class="footer">Generated by trnaseq abundance report module</div>
</body>
</html>"""

        output_path.write_text(html)
        return str(output_path)

    def _fig_to_div(self, fig):
        return plotly.offline.plot(fig, output_type='div', include_plotlyjs=False)

    # ---- panel 1: volcano ----

    def _panel_volcano(self):
        """Volcano plot of DE results."""
        df = self.results
        if df.empty or 'padj' not in df.columns or 'log2FoldChange' not in df.columns:
            return ''

        padj_threshold = 0.05
        lfc_threshold = 1.0

        df = df.copy()
        df['-log10(padj)'] = -np.log10(df['padj'].clip(lower=1e-300))

        sig_up = (df['padj'] < padj_threshold) & (df['log2FoldChange'] > lfc_threshold)
        sig_down = (df['padj'] < padj_threshold) & (df['log2FoldChange'] < -lfc_threshold)
        ns = ~(sig_up | sig_down)

        fig = go.Figure()
        for mask, name, color in [
            (ns, 'Not significant', '#b2bec3'),
            (sig_up, 'Up', '#d63031'),
            (sig_down, 'Down', '#0984e3'),
        ]:
            sub = df[mask]
            if sub.empty:
                continue
            fig.add_trace(go.Scatter(
                x=sub['log2FoldChange'],
                y=sub['-log10(padj)'],
                mode='markers',
                name=name,
                marker=dict(color=color, size=6, opacity=0.7),
                text=sub.get('feature', ''),
                hovertemplate='%{text}<br>LFC: %{x:.2f}<br>-log10(padj): %{y:.2f}',
            ))

        fig.add_hline(y=-np.log10(padj_threshold), line_dash='dash', line_color='gray')
        fig.add_vline(x=lfc_threshold, line_dash='dash', line_color='gray')
        fig.add_vline(x=-lfc_threshold, line_dash='dash', line_color='gray')

        fig.update_layout(
            title='Volcano Plot: Differential tRNA Abundance',
            xaxis_title='log2(Fold Change)',
            yaxis_title='-log10(adjusted p-value)',
            height=550,
        )
        div = self._fig_to_div(fig)
        return f'<h2>Volcano Plot</h2><div class="card">{div}</div>'

    # ---- panel 2: MA plot ----

    def _panel_ma(self):
        """MA plot of DE results."""
        df = self.results
        if df.empty or 'baseMean' not in df.columns:
            return ''

        padj_threshold = 0.05
        df = df.copy()
        sig = df['padj'] < padj_threshold

        fig = go.Figure()
        for mask, name, color in [
            (~sig, 'Not significant', '#b2bec3'),
            (sig, 'Significant', '#d63031'),
        ]:
            sub = df[mask]
            if sub.empty:
                continue
            fig.add_trace(go.Scatter(
                x=sub['baseMean'],
                y=sub['log2FoldChange'],
                mode='markers',
                name=name,
                marker=dict(color=color, size=6, opacity=0.7),
                text=sub.get('feature', ''),
                hovertemplate='%{text}<br>baseMean: %{x:.1f}<br>LFC: %{y:.2f}',
            ))

        fig.add_hline(y=0, line_color='black', opacity=0.3)
        fig.update_layout(
            title='MA Plot: Differential tRNA Abundance',
            xaxis_title='Mean of normalized counts',
            xaxis_type='log',
            yaxis_title='log2(Fold Change)',
            height=550,
        )
        div = self._fig_to_div(fig)
        return f'<h2>MA Plot</h2><div class="card">{div}</div>'

    # ---- panel 3: top DE table ----

    def _panel_top_de_table(self):
        """HTML table of top 20 most significant DE features."""
        df = self.results
        if df.empty or 'padj' not in df.columns:
            return ''

        top = df.nsmallest(20, 'padj')
        if top.empty:
            return ''

        display_cols = ['feature', 'log2FoldChange', 'padj', 'baseMean', 'comparison']
        display_cols = [c for c in display_cols if c in top.columns]

        header = ''.join(f'<th>{c}</th>' for c in display_cols)
        rows = []
        for _, row in top.iterrows():
            cells = []
            for col in display_cols:
                val = row[col]
                css = ''
                if col == 'log2FoldChange':
                    if val > 0:
                        css = ' class="up"'
                    elif val < 0:
                        css = ' class="down"'
                if isinstance(val, float):
                    if col == 'padj':
                        fmt_val = f'{val:.2e}'
                    else:
                        fmt_val = f'{val:.2f}'
                else:
                    fmt_val = str(val)
                cells.append(f'<td{css}>{fmt_val}</td>')
            rows.append('<tr>' + ''.join(cells) + '</tr>')

        return f"""
<h2>Top Differentially Expressed Features</h2>
<div class="card">
<table>
<tr>{header}</tr>
{''.join(rows)}
</table>
</div>"""

    # ---- panel 4: PCA ----

    def _panel_pca(self):
        """PCA of count matrix (log-transformed, SVD-based)."""
        cm = self.count_matrix
        if cm.empty or cm.shape[0] < 3:
            return ''

        # Log-transform (log2(count + 1))
        X = np.log2(cm.values.astype(float) + 1)
        X_centered = X - X.mean(axis=0)

        try:
            U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)
        except np.linalg.LinAlgError:
            return ''

        pc1 = U[:, 0] * S[0]
        pc2 = U[:, 1] * S[1]
        var_explained = (S ** 2) / (S ** 2).sum() * 100

        samples = cm.index.tolist()

        # Color by condition group
        if self.condition_map:
            groups = [str(self.condition_map.get(s, s)) for s in samples]
        else:
            groups = samples

        unique_groups = list(dict.fromkeys(groups))
        palette = _discrete_palette(len(unique_groups))
        color_map = {g: palette[i] for i, g in enumerate(unique_groups)}

        fig = go.Figure()
        for group in unique_groups:
            mask = [i for i, g in enumerate(groups) if g == group]
            fig.add_trace(go.Scatter(
                x=[pc1[i] for i in mask],
                y=[pc2[i] for i in mask],
                mode='markers+text',
                text=[samples[i] for i in mask],
                textposition='top right',
                textfont_size=9,
                marker=dict(size=10, color=color_map[group]),
                name=group,
            ))

        fig.update_layout(
            title='PCA of tRNA Count Matrix',
            xaxis_title=f'PC1 ({var_explained[0]:.1f}%)',
            yaxis_title=f'PC2 ({var_explained[1]:.1f}%)',
            height=500,
        )
        div = self._fig_to_div(fig)
        return f'<h2>PCA</h2><div class="card">{div}</div>'
