"""
Abundance QC Report Generator
================================

Generates abundance_report.html — an interactive Plotly dashboard
summarizing differential tRNA abundance analysis.

Panels:
    1. PCA of count matrix
    2. Per-comparison Volcano plot (dropdown)
    3. Per-comparison MA plot (dropdown)
    4. Top Variable Features Heatmap (z-scored RPM across conditions)
    5. RPM Distribution Violin plot
"""

import numpy as np
import pandas as pd
from pathlib import Path
from typing import Optional

import plotly.graph_objects as go
import plotly.offline

from trnaseq.qc.report import _discrete_palette


class AbundanceReportGenerator:
    """Generate interactive HTML dashboard for abundance analysis."""

    def __init__(
        self,
        results_df: pd.DataFrame,
        count_matrix: pd.DataFrame,
        control_group: str,
        level: str,
        condition_map: Optional[dict] = None,
    ):
        """
        Parameters
        ----------
        results_df : DataFrame
            DESeq2 results with columns: feature, log2FoldChange, padj,
            baseMean, comparison.
        count_matrix : DataFrame
            samples x features count matrix.
        control_group : str
            Name of the control group.
        level : str
            Aggregation level (transcript, codon, aa).
        condition_map : dict, optional
            {sample_name_unique: condition_group}.
        """
        self.results = results_df.copy() if results_df is not None else pd.DataFrame()
        self.count_matrix = count_matrix.copy()
        self.control_group = control_group
        self.level = level
        self.condition_map = condition_map or {}

    def generate_html_report(self, output_path) -> str:
        """Generate self-contained HTML report."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        panels = []

        p1 = self._panel_pca()
        if p1:
            panels.append(p1)

        p2 = self._panel_volcano()
        if p2:
            panels.append(p2)

        p3 = self._panel_ma()
        if p3:
            panels.append(p3)

        p4 = self._panel_variable_features_heatmap()
        if p4:
            panels.append(p4)

        p5 = self._panel_rpm_violin()
        if p5:
            panels.append(p5)

        body = '\n'.join(panels)
        plotlyjs = plotly.offline.get_plotlyjs()

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>tRNA Abundance Report</title>
<script>{plotlyjs}</script>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
       margin: 0; padding: 20px 40px; background: #f5f6fa; color: #2d3436; }}
h1 {{ border-bottom: 3px solid #6c5ce7; padding-bottom: 10px; }}
h2 {{ color: #2d3436; margin-top: 40px; }}
.card {{ background: white; border-radius: 8px; padding: 20px; margin: 20px 0;
         box-shadow: 0 2px 8px rgba(0,0,0,0.08); overflow-x: auto; }}
table {{ border-collapse: collapse; width: 100%; font-size: 13px; }}
th {{ background: #6c5ce7; color: white; padding: 8px 12px; text-align: left; }}
td {{ padding: 6px 12px; border-bottom: 1px solid #dfe6e9; }}
tr:hover {{ background: #f0f3f8; }}
.up {{ color: #d63031; font-weight: bold; }}
.down {{ color: #0984e3; font-weight: bold; }}
.footer {{ font-size: 11px; color: #636e72; margin-top: 40px; text-align: center; }}
</style>
</head>
<body>
<h1>tRNA Abundance Dashboard</h1>
<p>{'All pairwise comparisons' if not self.control_group else f'Control group: <code>{self.control_group}</code>'} | Level: <code>{self.level}</code></p>
{body}
<div class="footer">Generated by trnaseq abundance report module</div>
</body>
</html>"""

        output_path.write_text(html)
        return str(output_path)

    def _fig_to_div(self, fig):
        return plotly.offline.plot(fig, output_type='div', include_plotlyjs=False)

    # ---- panel 1: PCA ----

    def _panel_pca(self):
        """PCA of count matrix (log-transformed, SVD-based)."""
        cm = self.count_matrix
        if cm.empty or cm.shape[0] < 3:
            return ''

        # Log-transform (log2(count + 1))
        X = np.log2(cm.values.astype(float) + 1)
        X_centered = X - X.mean(axis=0)

        try:
            U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)
        except np.linalg.LinAlgError:
            return ''

        pc1 = U[:, 0] * S[0]
        pc2 = U[:, 1] * S[1]
        var_explained = (S ** 2) / (S ** 2).sum() * 100

        samples = cm.index.tolist()

        # Color by condition group
        if self.condition_map:
            groups = [str(self.condition_map.get(s, s)) for s in samples]
        else:
            groups = samples

        unique_groups = list(dict.fromkeys(groups))
        palette = _discrete_palette(len(unique_groups))
        color_map = {g: palette[i] for i, g in enumerate(unique_groups)}

        fig = go.Figure()
        for group in unique_groups:
            mask = [i for i, g in enumerate(groups) if g == group]
            fig.add_trace(go.Scatter(
                x=[pc1[i] for i in mask],
                y=[pc2[i] for i in mask],
                mode='markers+text',
                text=[samples[i] for i in mask],
                textposition='top right',
                textfont_size=9,
                marker=dict(size=10, color=color_map[group]),
                name=group,
            ))

        fig.update_layout(
            title='PCA of tRNA Count Matrix',
            xaxis_title=f'PC1 ({var_explained[0]:.1f}%)',
            yaxis_title=f'PC2 ({var_explained[1]:.1f}%)',
            height=500,
        )
        div = self._fig_to_div(fig)
        return f'<h2>PCA</h2><div class="card">{div}</div>'

    # ---- panel 2: volcano (per-comparison dropdown) ----

    def _panel_volcano(self):
        """Per-comparison volcano plot with dropdown selector."""
        df = self.results
        if df.empty or 'padj' not in df.columns or 'log2FoldChange' not in df.columns:
            return ''
        if 'comparison' not in df.columns:
            return ''

        padj_threshold = 0.05
        lfc_threshold = 1.0

        df = df.copy()
        df['-log10(padj)'] = -np.log10(df['padj'].clip(lower=1e-300))

        comparisons = sorted(df['comparison'].dropna().unique().tolist())
        if not comparisons:
            return ''

        fig = go.Figure()
        traces_per_comp = []

        for comp_idx, comp in enumerate(comparisons):
            sub_df = df[df['comparison'] == comp]

            sig_up = (sub_df['padj'] < padj_threshold) & (sub_df['log2FoldChange'] > lfc_threshold)
            sig_down = (sub_df['padj'] < padj_threshold) & (sub_df['log2FoldChange'] < -lfc_threshold)
            ns = ~(sig_up | sig_down)

            n_traces = 0
            for mask, name, color in [
                (ns, 'Not significant', '#b2bec3'),
                (sig_up, 'Up', '#d63031'),
                (sig_down, 'Down', '#0984e3'),
            ]:
                sub = sub_df[mask]
                fig.add_trace(go.Scatter(
                    x=sub['log2FoldChange'],
                    y=sub['-log10(padj)'],
                    mode='markers',
                    name=name,
                    visible=(comp_idx == 0),
                    marker=dict(color=color, size=6, opacity=0.7),
                    text=sub.get('feature', pd.Series([], dtype=str)),
                    hovertemplate='%{text}<br>LFC: %{x:.2f}<br>-log10(padj): %{y:.2f}',
                    showlegend=(comp_idx == 0),
                ))
                n_traces += 1
            traces_per_comp.append(n_traces)

        total = sum(traces_per_comp)
        buttons = []
        offset = 0
        for comp_idx, comp in enumerate(comparisons):
            n_t = traces_per_comp[comp_idx]
            vis = [False] * total
            for j in range(n_t):
                vis[offset + j] = True
            buttons.append(dict(
                label=comp,
                method='update',
                args=[
                    {'visible': vis},
                    {'title': f'Volcano Plot: {comp}'},
                ],
            ))
            offset += n_t

        fig.add_hline(y=-np.log10(padj_threshold), line_dash='dash', line_color='gray')
        fig.add_vline(x=lfc_threshold, line_dash='dash', line_color='gray')
        fig.add_vline(x=-lfc_threshold, line_dash='dash', line_color='gray')

        fig.update_layout(
            title=f'Volcano Plot: {comparisons[0]}',
            xaxis_title='log2(Fold Change)',
            yaxis_title='-log10(adjusted p-value)',
            height=550,
            updatemenus=[dict(
                buttons=buttons,
                direction='down',
                showactive=True,
                x=1.0,
                xanchor='right',
                y=1.15,
                yanchor='top',
            )],
        )
        div = self._fig_to_div(fig)
        return f'<h2>Volcano Plot</h2><div class="card">{div}</div>'

    # ---- panel 3: MA plot (per-comparison dropdown) ----

    def _panel_ma(self):
        """Per-comparison MA plot with dropdown selector."""
        df = self.results
        if df.empty or 'baseMean' not in df.columns:
            return ''
        if 'comparison' not in df.columns:
            return ''

        padj_threshold = 0.05
        df = df.copy()

        comparisons = sorted(df['comparison'].dropna().unique().tolist())
        if not comparisons:
            return ''

        fig = go.Figure()
        traces_per_comp = []

        for comp_idx, comp in enumerate(comparisons):
            sub_df = df[df['comparison'] == comp]
            sig = sub_df['padj'] < padj_threshold

            n_traces = 0
            for mask, name, color in [
                (~sig, 'Not significant', '#b2bec3'),
                (sig, 'Significant', '#d63031'),
            ]:
                sub = sub_df[mask]
                fig.add_trace(go.Scatter(
                    x=sub['baseMean'],
                    y=sub['log2FoldChange'],
                    mode='markers',
                    name=name,
                    visible=(comp_idx == 0),
                    marker=dict(color=color, size=6, opacity=0.7),
                    text=sub.get('feature', pd.Series([], dtype=str)),
                    hovertemplate='%{text}<br>baseMean: %{x:.1f}<br>LFC: %{y:.2f}',
                    showlegend=(comp_idx == 0),
                ))
                n_traces += 1
            traces_per_comp.append(n_traces)

        total = sum(traces_per_comp)
        buttons = []
        offset = 0
        for comp_idx, comp in enumerate(comparisons):
            n_t = traces_per_comp[comp_idx]
            vis = [False] * total
            for j in range(n_t):
                vis[offset + j] = True
            buttons.append(dict(
                label=comp,
                method='update',
                args=[
                    {'visible': vis},
                    {'title': f'MA Plot: {comp}'},
                ],
            ))
            offset += n_t

        fig.add_hline(y=0, line_color='black', opacity=0.3)
        fig.update_layout(
            title=f'MA Plot: {comparisons[0]}',
            xaxis_title='Mean of normalized counts',
            xaxis_type='log',
            yaxis_title='log2(Fold Change)',
            height=550,
            updatemenus=[dict(
                buttons=buttons,
                direction='down',
                showactive=True,
                x=1.0,
                xanchor='right',
                y=1.15,
                yanchor='top',
            )],
        )
        div = self._fig_to_div(fig)
        return f'<h2>MA Plot</h2><div class="card">{div}</div>'

    # ---- panel 4: top variable features heatmap ----

    def _panel_variable_features_heatmap(self):
        """Heatmap of top 20 most significant features (z-scored RPM, conditions x features)."""
        df = self.results
        cm = self.count_matrix

        if df.empty or cm.empty:
            return ''
        if 'padj' not in df.columns or 'feature' not in df.columns:
            return ''

        # Select top 20 features by smallest padj across any comparison
        top_df = (
            df.dropna(subset=['padj'])
            .sort_values('padj')
            .drop_duplicates(subset=['feature'])
            .head(20)
        )
        top_features = top_df['feature'].tolist()
        if not top_features:
            return ''

        # Keep only features present in the count matrix
        cols_available = [f for f in top_features if f in cm.columns]
        if not cols_available:
            return ''

        # Compute RPM per sample
        counts = cm[cols_available].values.astype(float)
        sample_sums = cm.values.astype(float).sum(axis=1, keepdims=True)
        sample_sums = np.where(sample_sums == 0, 1, sample_sums)
        rpm = counts / sample_sums * 1e6  # shape: (n_samples, n_features)

        # Z-score normalize each feature across samples
        feat_mean = rpm.mean(axis=0)
        feat_std = rpm.std(axis=0)
        feat_std = np.where(feat_std == 0, 1, feat_std)
        z = (rpm - feat_mean) / feat_std  # shape: (n_samples, n_features)

        samples = cm.index.tolist()

        # Map samples to conditions; fall back to sample name
        if self.condition_map:
            conditions = [str(self.condition_map.get(s, s)) for s in samples]
        else:
            conditions = samples

        # Build a DataFrame for groupby
        z_df = pd.DataFrame(z, index=samples, columns=cols_available)
        z_df['_condition'] = conditions

        condition_means = z_df.groupby('_condition')[cols_available].mean()
        sorted_conditions = sorted(condition_means.index.tolist())
        condition_means = condition_means.loc[sorted_conditions]

        # Shorten feature labels: strip prefix before first '-'
        def _shorten(name):
            parts = name.split('-', 1)
            return parts[1] if len(parts) == 2 else name

        y_labels = [_shorten(f) for f in cols_available]

        n_features = len(cols_available)
        height = max(400, n_features * 25 + 150)

        fig = go.Figure(go.Heatmap(
            z=condition_means.values.T,          # features x conditions
            x=sorted_conditions,
            y=y_labels,
            colorscale='RdBu_r',
            zmid=0,
            colorbar=dict(title='z-score'),
            hovertemplate='Condition: %{x}<br>Feature: %{y}<br>z-score: %{z:.2f}<extra></extra>',
        ))

        fig.update_layout(
            title='Top Differentially Abundant tRNAs (z-scored RPM)',
            xaxis_title='Condition',
            yaxis_title='tRNA',
            xaxis_tickangle=-45,
            height=height,
        )

        div = self._fig_to_div(fig)
        return f'<h2>Top Variable Features</h2><div class="card">{div}</div>'

    # ---- panel 5: RPM distribution violin ----

    def _panel_rpm_violin(self):
        """Violin/box plot of log2(RPM+1) per sample, colored by condition."""
        cm = self.count_matrix
        if cm.empty:
            return ''

        counts = cm.values.astype(float)
        sample_sums = counts.sum(axis=1, keepdims=True)
        # Avoid division by zero for samples with no counts
        sample_sums = np.where(sample_sums == 0, 1, sample_sums)
        rpm = counts / sample_sums * 1e6
        log_rpm = np.log2(rpm + 1)

        samples = cm.index.tolist()

        if self.condition_map:
            groups = [str(self.condition_map.get(s, s)) for s in samples]
        else:
            groups = samples

        unique_groups = list(dict.fromkeys(groups))
        palette = _discrete_palette(len(unique_groups))
        color_map = {g: palette[i] for i, g in enumerate(unique_groups)}

        fig = go.Figure()
        for i, sample in enumerate(samples):
            group = groups[i]
            fig.add_trace(go.Box(
                y=log_rpm[i],
                name=sample,
                marker_color=color_map[group],
                legendgroup=group,
                legendgrouptitle_text=group if i == groups.index(group) else None,
                showlegend=True,
                boxmean=True,
            ))

        fig.update_layout(
            title='RPM Distribution per Sample',
            xaxis_title='Sample',
            yaxis_title='log2(RPM + 1)',
            height=500,
            xaxis_tickangle=-45,
        )
        div = self._fig_to_div(fig)
        return f'<h2>RPM Distribution</h2><div class="card">{div}</div>'

