"""
Fragment QC Report Generator
==============================

Generates fragment_report.html — an interactive Plotly dashboard
summarizing tRNA fragment analysis across samples.

Panels:
    1. Fragment type stacked bar
    2. Per-tRNA integrity heatmap (top 50 tRNAs)
    3. RT drop-off positional profile (top 5 tRNAs)
    4. Fragment length distribution
    5. Behrens coverage plot (if coverage data provided)
    6. Needle coverage plot (if coverage data provided)
    7. Synthetic tRNA integrity (if source_prefixes provided)
"""

import numpy as np
import pandas as pd
from pathlib import Path
from typing import Optional

import plotly.graph_objects as go
import plotly.offline

from trnaseq.qc.report import _discrete_palette


def _isoacceptor_sort_key(trna_name):
    """Sort key for tRNA names by amino acid then anticodon."""
    parts = trna_name.split('-')
    if len(parts) >= 3:
        return (parts[1], parts[2])
    return (trna_name, '')


# Standard amino acid order for consistent coloring across plots
_AA_ORDER = [
    'Ala', 'Arg', 'Asn', 'Asp', 'Cys', 'Gln', 'Glu', 'Gly',
    'His', 'Ile', 'Leu', 'Lys', 'Met', 'Phe', 'Pro', 'Ser',
    'Thr', 'Trp', 'Tyr', 'Val',
]


def _aa_palette():
    """Return a {amino_acid: hex_color} mapping using tab20."""
    palette = _discrete_palette(20)
    return {aa: palette[i] for i, aa in enumerate(_AA_ORDER)}


class FragmentReportGenerator:
    """Generate interactive HTML dashboard for fragment analysis QC."""

    MAX_TRNAS_HEATMAP = 50

    def __init__(
        self,
        fragment_counts_df: pd.DataFrame,
        rt_dropoff_df: pd.DataFrame,
        fragment_lengths_df: pd.DataFrame,
        fragment_summary_df: pd.DataFrame,
        sample_df: pd.DataFrame,
        coverage_df: Optional[pd.DataFrame] = None,
        source_prefixes: Optional[dict] = None,
    ):
        """
        Parameters
        ----------
        fragment_counts_df : DataFrame
            Per-tRNA per-sample fragment counts with integrity_score.
        rt_dropoff_df : DataFrame
            RT drop-off positional data (position, rt_stop_fraction).
        fragment_lengths_df : DataFrame
            Fragment length distributions.
        fragment_summary_df : DataFrame
            Per-sample summary (N_full_length, N_rt_dropoff, etc.).
        sample_df : DataFrame
            Sample metadata.
        coverage_df : DataFrame, optional
            Per-sample per-AA per-position coverage data from FragmentAnalyser.
            Columns: sample_name_unique, amino_acid, position, count, max_tRNA_len.
        source_prefixes : dict, optional
            {prefix: category} for classifying tRNA sources (e.g. synthetic).
        """
        self.frag_counts = fragment_counts_df.copy()
        self.rt_dropoff = rt_dropoff_df.copy()
        self.frag_lengths = fragment_lengths_df.copy()
        self.frag_summary = fragment_summary_df.copy()
        self.sample_df = sample_df.copy()
        self.coverage_df = coverage_df.copy() if coverage_df is not None else None
        self.source_prefixes = source_prefixes

    def generate_html_report(self, output_path) -> str:
        """Generate self-contained HTML report."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        panels = []

        p1 = self._panel_fragment_type_bar()
        if p1:
            panels.append(p1)

        p2 = self._panel_integrity_heatmap()
        if p2:
            panels.append(p2)

        p3 = self._panel_rt_dropoff_profile()
        if p3:
            panels.append(p3)

        p4 = self._panel_fragment_length_distribution()
        if p4:
            panels.append(p4)

        p5 = self._panel_behrens_coverage()
        if p5:
            panels.append(p5)

        p6 = self._panel_needle_coverage()
        if p6:
            panels.append(p6)

        p7 = self._panel_synthetic_integrity()
        if p7:
            panels.append(p7)

        body = '\n'.join(panels)
        plotlyjs = plotly.offline.get_plotlyjs()

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>tRNA Fragment Report</title>
<script>{plotlyjs}</script>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
       margin: 0; padding: 20px 40px; background: #f5f6fa; color: #2d3436; }}
h1 {{ border-bottom: 3px solid #0984e3; padding-bottom: 10px; }}
h2 {{ color: #2d3436; margin-top: 40px; }}
.card {{ background: white; border-radius: 8px; padding: 20px; margin: 20px 0;
         box-shadow: 0 2px 8px rgba(0,0,0,0.08); overflow-x: auto; }}
.footer {{ font-size: 11px; color: #636e72; margin-top: 40px; text-align: center; }}
</style>
</head>
<body>
<h1>tRNA Fragment Dashboard</h1>
{body}
<div class="footer">Generated by trnaseq fragment report module</div>
</body>
</html>"""

        output_path.write_text(html)
        return str(output_path)

    def _fig_to_div(self, fig):
        return plotly.offline.plot(fig, output_type='div', include_plotlyjs=False)

    # ---- panel 1: fragment type stacked bar ----

    def _panel_fragment_type_bar(self):
        """Stacked bar of fragment types per sample."""
        df = self.frag_summary
        if df.empty:
            return ''

        type_cols = {
            'N_full_length': ('Full-length', '#00b894'),
            'N_rt_dropoff': ('RT drop-off', '#0984e3'),
            'N_5p_tRF': ("5' tRF", '#fdcb6e'),
            'N_degraded': ('Degraded', '#d63031'),
        }

        present = {k: v for k, v in type_cols.items() if k in df.columns}
        if not present:
            return ''

        fig = go.Figure()
        for col, (label, color) in present.items():
            fig.add_trace(go.Bar(
                x=df['sample_name_unique'],
                y=df[col],
                name=label,
                marker_color=color,
            ))
        fig.update_layout(
            barmode='stack',
            title='Fragment Type Distribution per Sample',
            yaxis_title='Read count',
            height=max(400, len(df) * 25),
        )
        div = self._fig_to_div(fig)
        return f'<h2>Fragment Types</h2><div class="card">{div}</div>'

    # ---- panel 2: integrity heatmap ----

    def _panel_integrity_heatmap(self):
        """Heatmap: top tRNAs x samples, color = integrity_score."""
        df = self.frag_counts
        if df.empty or 'integrity_score' not in df.columns:
            return ''

        trna_col = 'tRNA_annotation' if 'tRNA_annotation' in df.columns else 'tRNA_name'
        if trna_col not in df.columns:
            return ''

        # Select top tRNAs by total reads
        count_col = 'total_reads' if 'total_reads' in df.columns else 'count'
        if count_col not in df.columns:
            # Use integrity_score count as proxy
            top_trnas = df[trna_col].value_counts().head(self.MAX_TRNAS_HEATMAP).index.tolist()
        else:
            trna_totals = df.groupby(trna_col)[count_col].sum().nlargest(self.MAX_TRNAS_HEATMAP)
            top_trnas = trna_totals.index.tolist()

        # Sort by isoacceptor
        top_trnas = sorted(top_trnas, key=_isoacceptor_sort_key)

        sub = df[df[trna_col].isin(top_trnas)]
        pivot = sub.pivot_table(
            index=trna_col, columns='sample_name_unique',
            values='integrity_score', aggfunc='mean')

        # Reorder rows
        pivot = pivot.reindex([t for t in top_trnas if t in pivot.index])

        if pivot.empty:
            return ''

        fig = go.Figure(go.Heatmap(
            z=pivot.values,
            x=pivot.columns.tolist(),
            y=pivot.index.tolist(),
            colorscale='RdYlGn',
            zmin=0, zmax=1,
            colorbar=dict(title='Integrity'),
            hovertemplate='tRNA: %{y}<br>Sample: %{x}<br>Integrity: %{z:.2f}<extra></extra>',
        ))
        fig.update_layout(
            title=f'tRNA Integrity (top {len(pivot)} tRNAs)',
            height=max(400, len(pivot) * 18),
        )
        div = self._fig_to_div(fig)
        return f'<h2>tRNA Integrity Heatmap</h2><div class="card">{div}</div>'

    # ---- panel 3: RT drop-off profile ----

    def _panel_rt_dropoff_profile(self):
        """Line plot: RT drop-off positional profile for top tRNAs."""
        df = self.rt_dropoff
        if df.empty:
            return ''

        pos_col = 'position' if 'position' in df.columns else None
        frac_col = 'rt_stop_fraction' if 'rt_stop_fraction' in df.columns else None
        trna_col = 'tRNA_annotation' if 'tRNA_annotation' in df.columns else 'tRNA_name'

        if pos_col is None or frac_col is None or trna_col not in df.columns:
            return ''

        # Aggregate across samples, pick top 5 by total signal
        agg = df.groupby([trna_col, pos_col])[frac_col].mean().reset_index()
        trna_signal = agg.groupby(trna_col)[frac_col].sum().nlargest(5)
        top_trnas = trna_signal.index.tolist()

        if not top_trnas:
            return ''

        palette = _discrete_palette(len(top_trnas))
        fig = go.Figure()
        for i, trna in enumerate(top_trnas):
            sub = agg[agg[trna_col] == trna].sort_values(pos_col)
            # Shorten name for legend
            short = '-'.join(trna.split('-')[1:]) if '-' in trna else trna
            fig.add_trace(go.Scatter(
                x=sub[pos_col], y=sub[frac_col],
                mode='lines', name=short,
                line=dict(color=palette[i]),
            ))

        fig.update_layout(
            title='RT Drop-off Positional Profile (top 5 tRNAs)',
            xaxis_title='Position (nt)',
            yaxis_title='RT stop fraction',
            height=450,
        )
        div = self._fig_to_div(fig)
        return f'<h2>RT Drop-off Profile</h2><div class="card">{div}</div>'

    # ---- panel 4: fragment length distribution ----

    def _panel_fragment_length_distribution(self):
        """Overlaid line traces by fragment type (aggregated)."""
        df = self.frag_lengths
        if df.empty:
            return ''

        len_col = 'fragment_length' if 'fragment_length' in df.columns else 'read_length'
        count_col = 'read_count' if 'read_count' in df.columns else 'count'
        type_col = 'fragment_type' if 'fragment_type' in df.columns else None

        if len_col not in df.columns or count_col not in df.columns:
            return ''

        type_colors = {
            'full_length': '#00b894',
            'rt_dropoff': '#0984e3',
            '5p_tRF': '#fdcb6e',
            'degraded': '#d63031',
        }

        fig = go.Figure()

        if type_col and type_col in df.columns:
            for ftype in df[type_col].unique():
                sub = df[df[type_col] == ftype].groupby(len_col)[count_col].sum().reset_index()
                sub = sub.sort_values(len_col)
                fig.add_trace(go.Scatter(
                    x=sub[len_col], y=sub[count_col],
                    mode='lines', name=ftype,
                    line=dict(color=type_colors.get(ftype, '#b2bec3')),
                ))
        else:
            agg = df.groupby(len_col)[count_col].sum().reset_index().sort_values(len_col)
            fig.add_trace(go.Scatter(
                x=agg[len_col], y=agg[count_col],
                mode='lines', name='All fragments',
            ))

        fig.update_layout(
            title='Fragment Length Distribution',
            xaxis_title='Fragment length (nt)',
            yaxis_title='Read count',
            height=450,
        )
        div = self._fig_to_div(fig)
        return f'<h2>Fragment Length Distribution</h2><div class="card">{div}</div>'

    # ---- coverage normalization helper ----

    def _normalize_coverage_matrix(self, sample_cov, n_bins=100):
        """Normalize variable-length tRNA coverage to a common positional axis.

        For each amino acid, maps positions [0, max_tRNA_len) to [0, n_bins)
        using linear interpolation, then sums across amino acids.

        Parameters
        ----------
        sample_cov : DataFrame
            Subset of coverage_df for a single sample.
            Columns: amino_acid, position, count, max_tRNA_len.
        n_bins : int
            Number of bins in the normalized axis.

        Returns
        -------
        aa_matrix : dict
            {amino_acid: ndarray(n_bins,)} — normalized coverage per AA.
        total : ndarray(n_bins,)
            Sum across all amino acids.
        """
        aa_matrix = {}
        total = np.zeros(n_bins)

        for aa, grp in sample_cov.groupby('amino_acid'):
            max_len = int(grp['max_tRNA_len'].iloc[0])
            if max_len < 2:
                continue

            # Build raw coverage vector (cumulative 5'->3')
            raw = np.zeros(max_len)
            for _, row in grp.iterrows():
                pos = int(row['position'])
                if 0 <= pos < max_len:
                    raw[pos] += row['count']

            # Cumulative sum 5'->3' gives coverage at each position
            cum = np.cumsum(raw[::-1])[::-1]

            # Interpolate to normalized axis
            old_x = np.linspace(0, 1, max_len)
            new_x = np.linspace(0, 1, n_bins)
            interp = np.interp(new_x, old_x, cum)

            aa_matrix[aa] = interp
            total += interp

        return aa_matrix, total

    # ---- panel 5: Behrens coverage plot ----

    def _panel_behrens_coverage(self):
        """Stacked area chart of read coverage by amino acid (Behrens-style)."""
        if self.coverage_df is None or self.coverage_df.empty:
            return ''

        required = {'amino_acid', 'position', 'count', 'max_tRNA_len',
                     'sample_name_unique'}
        if not required.issubset(self.coverage_df.columns):
            return ''

        samples = sorted(self.coverage_df['sample_name_unique'].unique())
        if not samples:
            return ''

        aa_colors = _aa_palette()
        n_bins = 100

        # Build traces for each sample (first sample visible, rest hidden)
        fig = go.Figure()
        buttons = []

        for s_idx, sample in enumerate(samples):
            scov = self.coverage_df[
                self.coverage_df['sample_name_unique'] == sample
            ]
            aa_matrix, _ = self._normalize_coverage_matrix(scov, n_bins)

            x_axis = np.linspace(0, 100, n_bins)
            visible = (s_idx == 0)

            # Sort AAs for consistent stacking
            sorted_aas = [aa for aa in _AA_ORDER if aa in aa_matrix]
            for extra_aa in sorted(set(aa_matrix) - set(_AA_ORDER)):
                sorted_aas.append(extra_aa)

            for aa in sorted_aas:
                color = aa_colors.get(aa, '#b2bec3')
                fig.add_trace(go.Scatter(
                    x=x_axis,
                    y=aa_matrix[aa],
                    mode='lines',
                    name=aa,
                    stackgroup=f'stack_{s_idx}',
                    line=dict(width=0.5, color=color),
                    fillcolor=color,
                    visible=visible,
                    showlegend=(s_idx == 0),
                    hovertemplate=f'{aa}<br>'
                                 'Position: %{x:.0f}%<br>'
                                 'Coverage: %{y:.0f}<extra></extra>',
                ))

            # Button for dropdown
            n_aas = len(sorted_aas)
            vis = [False] * (len(samples) * n_aas) if n_aas > 0 else []
            start = s_idx * n_aas
            for j in range(n_aas):
                vis[start + j] = True
            buttons.append(dict(
                label=sample,
                method='update',
                args=[{'visible': vis}],
            ))

        if buttons:
            fig.update_layout(
                updatemenus=[dict(
                    type='dropdown',
                    direction='down',
                    x=1.0, xanchor='right',
                    y=1.15, yanchor='top',
                    buttons=buttons,
                    active=0,
                )],
            )

        fig.update_layout(
            title='tRNA Coverage by Amino Acid (Behrens Plot)',
            xaxis_title='Normalized position (% of tRNA length)',
            yaxis_title='Cumulative read starts',
            height=500,
        )
        div = self._fig_to_div(fig)
        return f'<h2>Behrens Coverage Plot</h2><div class="card">{div}</div>'

    # ---- panel 6: needle coverage plot ----

    def _panel_needle_coverage(self):
        """Needle plot: per-AA normalized coverage centered on 3' end."""
        if self.coverage_df is None or self.coverage_df.empty:
            return ''

        required = {'amino_acid', 'position', 'count', 'max_tRNA_len',
                     'sample_name_unique'}
        if not required.issubset(self.coverage_df.columns):
            return ''

        samples = sorted(self.coverage_df['sample_name_unique'].unique())
        if not samples:
            return ''

        aa_colors = _aa_palette()
        n_bins = 100

        fig = go.Figure()
        buttons = []

        for s_idx, sample in enumerate(samples):
            scov = self.coverage_df[
                self.coverage_df['sample_name_unique'] == sample
            ]
            aa_matrix, _ = self._normalize_coverage_matrix(scov, n_bins)

            x_axis = np.linspace(0, 100, n_bins)
            visible = (s_idx == 0)

            sorted_aas = [aa for aa in _AA_ORDER if aa in aa_matrix]
            for extra_aa in sorted(set(aa_matrix) - set(_AA_ORDER)):
                sorted_aas.append(extra_aa)

            for aa in sorted_aas:
                # Normalize each AA to its own 3' maximum
                vals = aa_matrix[aa]
                max_val = vals.max()
                normed = vals / max_val if max_val > 0 else vals

                color = aa_colors.get(aa, '#b2bec3')
                fig.add_trace(go.Scatter(
                    x=x_axis,
                    y=normed,
                    mode='lines',
                    name=aa,
                    line=dict(width=1.5, color=color),
                    visible=visible,
                    showlegend=(s_idx == 0),
                    hovertemplate=f'{aa}<br>'
                                 'Position: %{x:.0f}%<br>'
                                 'Relative coverage: %{y:.2f}<extra></extra>',
                ))

            n_aas = len(sorted_aas)
            vis = [False] * (len(samples) * n_aas) if n_aas > 0 else []
            start = s_idx * n_aas
            for j in range(n_aas):
                vis[start + j] = True
            buttons.append(dict(
                label=sample,
                method='update',
                args=[{'visible': vis}],
            ))

        if buttons:
            fig.update_layout(
                updatemenus=[dict(
                    type='dropdown',
                    direction='down',
                    x=1.0, xanchor='right',
                    y=1.15, yanchor='top',
                    buttons=buttons,
                    active=0,
                )],
            )

        fig.update_layout(
            title='Per-AA Normalized Coverage (Needle Plot)',
            xaxis_title='Normalized position (% of tRNA length)',
            yaxis_title='Relative coverage (AA-normalized)',
            height=500,
        )
        div = self._fig_to_div(fig)
        return f'<h2>Needle Coverage Plot</h2><div class="card">{div}</div>'

    # ---- panel 7: synthetic tRNA integrity ----

    def _panel_synthetic_integrity(self):
        """Bar chart of integrity scores for synthetic control tRNAs."""
        if not self.source_prefixes:
            return ''

        df = self.frag_counts
        if df.empty or 'integrity_score' not in df.columns:
            return ''

        trna_col = 'tRNA_annotation' if 'tRNA_annotation' in df.columns else 'tRNA_name'
        if trna_col not in df.columns:
            return ''

        from trnaseq.charge.quantifier import classify_trna_source

        df = df.copy()
        df['_source'] = df[trna_col].apply(
            lambda x: classify_trna_source(x, self.source_prefixes)
        )
        syn = df[df['_source'] == 'synthetic']
        if syn.empty:
            return ''

        samples = sorted(syn['sample_name_unique'].unique())
        trnas = sorted(syn[trna_col].unique(), key=_isoacceptor_sort_key)
        palette = _discrete_palette(len(samples))

        fig = go.Figure()
        for i, sample in enumerate(samples):
            ssub = syn[syn['sample_name_unique'] == sample]
            vals = []
            for t in trnas:
                row = ssub[ssub[trna_col] == t]
                vals.append(float(row['integrity_score'].iloc[0])
                            if not row.empty else np.nan)
            short_names = ['-'.join(t.split('-')[1:]) if '-' in t else t
                           for t in trnas]
            fig.add_trace(go.Bar(
                x=short_names,
                y=vals,
                name=sample,
                marker_color=palette[i],
            ))

        fig.update_layout(
            barmode='group',
            title='Synthetic Control tRNA Integrity',
            xaxis_title='Synthetic tRNA',
            yaxis_title='Integrity score',
            yaxis_range=[0, 1.05],
            height=max(400, len(trnas) * 30),
        )
        div = self._fig_to_div(fig)
        return (f'<h2>Synthetic Control Integrity</h2>'
                f'<div class="card">{div}</div>')
