"""
Modification QC Report Generator
=================================

Generates modification_report.html from modification analysis outputs.
Self-contained Plotly HTML dashboard — follows the same pattern as
``trnaseq.qc.report.QCReportGenerator``.

Panels:
    1. Per-sample modification count bar chart
    2. Replicate concordance heatmap (3'-aligned positions, isoacceptor sort)
    3. Cross-replicate mismatch scatter (Pearson R)
    4. Mean fold-change per modification type heatmap (consensus only)
"""

import numpy as np
import pandas as pd
from pathlib import Path
from typing import Dict, List, Optional

import plotly.graph_objects as go
import plotly.offline
from plotly.subplots import make_subplots


class ModificationReportGenerator:
    """Generate interactive HTML dashboard for modification QC."""

    MAX_PAIRS = 30
    MAX_TRNAS_HEATMAP = 50

    def __init__(
        self,
        per_sample_calls: Dict[str, pd.DataFrame],
        aggregated_calls: Optional[pd.DataFrame] = None,
        consensus_calls: Optional[pd.DataFrame] = None,
        replicate_groups: Optional[Dict[str, List[str]]] = None,
        ref_dict: Optional[Dict[str, dict]] = None,
        summary_df: Optional[pd.DataFrame] = None,
        source_prefixes: Optional[dict] = None,
    ):
        """
        Parameters
        ----------
        per_sample_calls : dict
            {sample_name_unique: calls DataFrame}.
        aggregated_calls : DataFrame, optional
            Output of ReplicateAggregator.aggregate() (all sites >=1 rep).
        consensus_calls : DataFrame, optional
            Subset where consensus_call==True.
        replicate_groups : dict, optional
            {condition: [sample_name_unique, ...]}.
        ref_dict : dict, optional
            {trna_name: {'seq': str, 'seq_len': int}} for 3' alignment.
        summary_df : DataFrame, optional
            modification_summary (one row per sample).
        source_prefixes : dict, optional
            {prefix: category} for classifying tRNA sources (e.g. synthetic).
        """
        self.per_sample_calls = per_sample_calls
        self.aggregated_calls = aggregated_calls
        self.consensus_calls = consensus_calls
        self.replicate_groups = replicate_groups
        self.ref_dict = ref_dict or {}
        self.summary_df = summary_df
        self.source_prefixes = source_prefixes

    # ------------------------------------------------------------------
    # Main entry
    # ------------------------------------------------------------------

    def generate_html_report(self, output_path):
        """Generate self-contained HTML report at *output_path*."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        panels = []

        # 1. Per-sample counts
        p1 = self._panel_per_sample_counts()
        if p1:
            panels.append(p1)

        # 2. Concordance heatmap
        p2 = self._panel_concordance_heatmap()
        if p2:
            panels.append(p2)

        # 3. Replicate scatter
        p3 = self._panel_replicate_scatter()
        if p3:
            panels.append(p3)

        # 4. FC heatmap
        p4 = self._panel_fc_heatmap()
        if p4:
            panels.append(p4)

        # 5. Synthetic false positives
        p5 = self._panel_synthetic_false_positives()
        if p5:
            panels.append(p5)

        body = '\n'.join(panels) if panels else '<p>No modification data available for report.</p>'

        plotlyjs = plotly.offline.get_plotlyjs()

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Modification QC Report</title>
<script>{plotlyjs}</script>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
       margin: 0; padding: 20px 40px; background: #f5f6fa; color: #2d3436; }}
h1 {{ border-bottom: 3px solid #6c5ce7; padding-bottom: 10px; }}
h2 {{ color: #2d3436; margin-top: 40px; }}
.card {{ background: white; border-radius: 8px; padding: 20px; margin: 20px 0;
         box-shadow: 0 2px 8px rgba(0,0,0,0.08); overflow-x: auto; }}
.footer {{ font-size: 11px; color: #636e72; margin-top: 40px; text-align: center; }}
</style>
</head>
<body>
<h1>Modification Analysis QC Dashboard</h1>
{body}
<div class="footer">Generated by trnaseq modification QC module</div>
</body>
</html>"""

        output_path.write_text(html)
        return str(output_path)

    # ---- helpers ----

    def _fig_to_div(self, fig):
        return plotly.offline.plot(fig, output_type='div', include_plotlyjs=False)

    @staticmethod
    def _isoacceptor_sort_key(trna_name: str) -> str:
        """Sort key: amino acid + anticodon extracted from FASTA name."""
        parts = trna_name.split('-')
        aa = parts[1] if len(parts) > 1 else ''
        ac = parts[2] if len(parts) > 2 else ''
        return f'{aa}-{ac}'

    # ------------------------------------------------------------------
    # Panel 1: per-sample modification counts
    # ------------------------------------------------------------------

    def _panel_per_sample_counts(self):
        if not self.per_sample_calls:
            return ''

        samples = sorted(self.per_sample_calls.keys())
        total_counts = []
        consensus_counts = []

        for s in samples:
            df = self.per_sample_calls[s]
            total_counts.append(len(df) if df is not None and not df.empty else 0)

        # If we have a summary_df, use consensus_calls from there
        has_consensus = (
            self.summary_df is not None
            and 'consensus_calls' in self.summary_df.columns
        )

        fig = go.Figure()
        fig.add_trace(go.Bar(
            x=samples,
            y=total_counts,
            name='Total calls',
            marker_color='#0984e3',
        ))

        if has_consensus:
            for s in samples:
                row = self.summary_df[self.summary_df['sample_name_unique'] == s]
                consensus_counts.append(
                    int(row['consensus_calls'].iloc[0]) if not row.empty else 0
                )
            fig.add_trace(go.Bar(
                x=samples,
                y=consensus_counts,
                name='Consensus calls',
                marker_color='#00b894',
            ))

        fig.update_layout(
            title='Modification Calls per Sample',
            yaxis_title='Number of modifications',
            barmode='group',
            height=max(350, len(samples) * 20 + 200),
        )
        div = self._fig_to_div(fig)
        return f'<h2>Per-Sample Modification Counts</h2><div class="card">{div}</div>'

    # ------------------------------------------------------------------
    # Panel 2: replicate concordance heatmap
    # ------------------------------------------------------------------

    def _panel_concordance_heatmap(self):
        if self.aggregated_calls is None or self.aggregated_calls.empty:
            return ''

        agg = self.aggregated_calls.copy()

        # Compute 3' offset if ref_dict available
        if self.ref_dict:
            def _3p_offset(row):
                info = self.ref_dict.get(row['trna_name'])
                if info:
                    return info['seq_len'] - int(row['position'])
                return -int(row['position'])  # fallback
            agg['offset_from_3p'] = agg.apply(_3p_offset, axis=1)
        else:
            agg['offset_from_3p'] = -agg['position'].astype(int)

        # Sort tRNAs by isoacceptor
        trnas = sorted(
            agg['trna_name'].unique(),
            key=self._isoacceptor_sort_key,
        )
        if len(trnas) > self.MAX_TRNAS_HEATMAP:
            trnas = trnas[:self.MAX_TRNAS_HEATMAP]
            agg = agg[agg['trna_name'].isin(trnas)]

        offsets = sorted(agg['offset_from_3p'].unique())

        # Build matrix: rows=tRNA, cols=3' offset, value=max n_replicates_detected
        matrix = np.full((len(trnas), len(offsets)), np.nan)
        trna_idx = {t: i for i, t in enumerate(trnas)}
        off_idx = {o: i for i, o in enumerate(offsets)}

        for _, row in agg.iterrows():
            ti = trna_idx.get(row['trna_name'])
            oi = off_idx.get(row['offset_from_3p'])
            if ti is not None and oi is not None:
                val = row['n_replicates_detected']
                if np.isnan(matrix[ti, oi]) or val > matrix[ti, oi]:
                    matrix[ti, oi] = val

        fig = go.Figure(go.Heatmap(
            z=matrix,
            x=[str(o) for o in offsets],
            y=trnas,
            colorscale='YlOrRd',
            colorbar_title='N replicates',
            hoverongaps=False,
        ))
        fig.update_layout(
            title='Replicate Concordance (positions as distance from 3\' end)',
            xaxis_title="Offset from 3' end",
            yaxis_title='tRNA (sorted by isoacceptor)',
            height=max(400, len(trnas) * 18 + 150),
        )
        div = self._fig_to_div(fig)
        return f'<h2>Replicate Concordance Heatmap</h2><div class="card">{div}</div>'

    # ------------------------------------------------------------------
    # Panel 3: cross-replicate mismatch scatter
    # ------------------------------------------------------------------

    def _panel_replicate_scatter(self):
        if not self.replicate_groups or not self.per_sample_calls:
            return ''

        pairs = []
        for condition, members in self.replicate_groups.items():
            present = [m for m in members if m in self.per_sample_calls
                       and self.per_sample_calls[m] is not None
                       and not self.per_sample_calls[m].empty]
            if len(present) >= 2:
                for i in range(len(present)):
                    for j in range(i + 1, len(present)):
                        pairs.append((present[i], present[j], condition))

        if not pairs:
            return ''

        if len(pairs) > self.MAX_PAIRS:
            return (
                '<h2>Cross-Replicate Mismatch Scatter</h2>'
                f'<div class="card"><p>Skipped: {len(pairs)} replicate pairs '
                f'exceeds display limit ({self.MAX_PAIRS}).</p></div>'
            )

        n_pairs = len(pairs)
        cols = min(3, n_pairs)
        rows = (n_pairs + cols - 1) // cols

        fig = make_subplots(
            rows=rows, cols=cols,
            subplot_titles=[f'{a} vs {b}' for a, b, _ in pairs],
        )

        for idx, (s1, s2, cond) in enumerate(pairs):
            r, c = divmod(idx, cols)

            df1 = self.per_sample_calls[s1]
            df2 = self.per_sample_calls[s2]

            # Merge on (trna_name, position, modification)
            merged = df1.merge(
                df2,
                on=['trna_name', 'position', 'modification'],
                suffixes=('_1', '_2'),
                how='inner',
            )
            if merged.empty:
                continue

            x = merged['mismatch_rate_1'].values
            y = merged['mismatch_rate_2'].values

            pearson_r = np.corrcoef(x, y)[0, 1] if len(x) > 1 else np.nan

            fig.add_trace(go.Scatter(
                x=x, y=y, mode='markers',
                marker=dict(size=4, opacity=0.6),
                name=f'{cond} R={pearson_r:.3f}',
            ), row=r + 1, col=c + 1)

            # Diagonal
            max_val = max(x.max(), y.max()) if len(x) > 0 else 1
            fig.add_trace(go.Scatter(
                x=[0, max_val], y=[0, max_val],
                mode='lines', line=dict(dash='dash', color='gray'),
                showlegend=False,
            ), row=r + 1, col=c + 1)

            ax_suffix = '' if idx == 0 else str(idx + 1)
            fig.add_annotation(
                x=0.05, y=0.95,
                xref=f'x{ax_suffix} domain', yref=f'y{ax_suffix} domain',
                text=f'R = {pearson_r:.3f}', showarrow=False,
                font=dict(size=12, color='red'),
            )

        fig.update_layout(
            title='Cross-Replicate Mismatch Rate Scatter',
            height=350 * rows,
        )
        div = self._fig_to_div(fig)
        return f'<h2>Cross-Replicate Mismatch Scatter</h2><div class="card">{div}</div>'

    # ------------------------------------------------------------------
    # Panel 4: fold-change heatmap (consensus only)
    # ------------------------------------------------------------------

    def _panel_fc_heatmap(self):
        if self.consensus_calls is None or self.consensus_calls.empty:
            return ''
        if 'mean_fold_change' not in self.consensus_calls.columns:
            return ''

        cc = self.consensus_calls.copy()

        # Aggregate: rows=modification type, cols=sample_name (condition)
        pivot = cc.pivot_table(
            index='modification',
            columns='sample_name',
            values='mean_fold_change',
            aggfunc='mean',
        )

        if pivot.empty:
            return ''

        # log2(FC + 1)
        z = np.log2(pivot.values + 1)

        fig = go.Figure(go.Heatmap(
            z=z,
            x=list(pivot.columns),
            y=list(pivot.index),
            colorscale='Viridis',
            colorbar_title='log2(FC+1)',
        ))
        fig.update_layout(
            title='Mean Fold-Change per Modification Type (Consensus Calls)',
            xaxis_title='Condition',
            yaxis_title='Modification',
            height=max(300, len(pivot.index) * 30 + 150),
        )
        div = self._fig_to_div(fig)
        return f'<h2>Fold-Change Heatmap (Consensus)</h2><div class="card">{div}</div>'

    # ------------------------------------------------------------------
    # Panel 5: synthetic tRNA false positives
    # ------------------------------------------------------------------

    def _panel_synthetic_false_positives(self):
        """Bar chart of modification calls on synthetic control tRNAs."""
        if not self.source_prefixes or not self.per_sample_calls:
            return ''

        from trnaseq.charge.quantifier import classify_trna_source

        # Collect all calls across samples for synthetic tRNAs
        syn_counts = {}  # {sample: n_calls_on_synthetics}
        syn_details = []

        for sample, calls_df in self.per_sample_calls.items():
            if calls_df is None or calls_df.empty:
                syn_counts[sample] = 0
                continue

            trna_col = 'trna_name' if 'trna_name' in calls_df.columns else None
            if trna_col is None:
                syn_counts[sample] = 0
                continue

            calls_df = calls_df.copy()
            calls_df['_source'] = calls_df[trna_col].apply(
                lambda x: classify_trna_source(x, self.source_prefixes)
            )
            syn_calls = calls_df[calls_df['_source'] == 'synthetic']
            syn_counts[sample] = len(syn_calls)

            if not syn_calls.empty:
                detail = syn_calls[[trna_col]].copy()
                detail['sample'] = sample
                # Include available detail columns
                for col in ['position', 'modification', 'mismatch_rate', 'fold_change']:
                    if col in syn_calls.columns:
                        detail[col] = syn_calls[col].values
                syn_details.append(detail)

        # If no synthetic calls at all, show a positive confirmation
        total_syn_calls = sum(syn_counts.values())

        samples = sorted(syn_counts.keys())
        counts = [syn_counts[s] for s in samples]

        fig = go.Figure(go.Bar(
            x=samples,
            y=counts,
            marker_color=['#00b894' if c == 0 else '#d63031' for c in counts],
            text=counts,
            textposition='auto',
        ))

        # Add background error rate annotation if available
        bg_text = ''
        if self.summary_df is not None and 'background_error_rate' in self.summary_df.columns:
            bg_rate = self.summary_df['background_error_rate'].mean()
            bg_source = (self.summary_df['bg_source'].iloc[0]
                         if 'bg_source' in self.summary_df.columns else 'unknown')
            bg_text = (f'<br><i>Background error rate: {bg_rate:.4f} '
                       f'(source: {bg_source})</i>')

        fig.update_layout(
            title=f'Modification Calls on Synthetic Controls '
                  f'(total: {total_syn_calls}, expected: 0)',
            xaxis_title='Sample',
            yaxis_title='Number of false-positive calls',
            height=max(350, len(samples) * 20 + 200),
        )

        div = self._fig_to_div(fig)

        # Build detail table if any false positives exist
        detail_html = ''
        if syn_details:
            detail_df = pd.concat(syn_details, ignore_index=True)
            detail_html = (
                '<h3>False Positive Details</h3>'
                '<div style="overflow-x:auto; max-height:300px">'
                + detail_df.to_html(index=False, classes='', border=0)
                + '</div>'
            )

        return (f'<h2>Synthetic Control False Positives</h2>'
                f'<div class="card">{div}{bg_text}{detail_html}</div>')
